# This workflow builds and deploys the Flutter web app to Firebase Hosting.

name: Frontend CI/CD

on:
  push:
    branches:
      - main # Triggers on push to the main branch
    paths:
      # Corrected paths to match your project structure
      - 'lib/**'
      - 'assets/**'
      - 'pubspec.yaml'
      - '.github/workflows/frontend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        # DELETED: working-directory: ./frontend

      - name: Build Flutter Web App
        run: flutter build web --release
        # DELETED: working-directory: ./frontend

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FORESEE_CYCLES }}'
          channelId: live
          projectId: ${{ secrets.GCP_PROJECT_ID }}
          # DELETED: entryPoint: ./frontend
